### ISSUE TITLE
TNBC Mobile Wallet

### ISSUE THREAD

**Issue by wakawakathedev** [thenewboston-developers/Project-Proposals#323]
# Project Details

#### How would you describe your project?
TNBC Mobile Wallet - work can be found [here](https://github.com/wakawakathedev/tnbc_mobile_template) 

#### What problem does this project solve?
Open-source MIT Version of mobile wallet.

#### Who is the target market?
Developers and other startups that want to release a Mobile wallet businesses.

#### How will this project benefit the network and/or the community?
We have Keysign as a consumer app, but other developers may wish to launch their own app (with custom designs/assets).
It also means that this project can allow developers to understand how the mobile wallet works (and integrate their own APIs and other funcitonality for their respective Wallets)

#### How is this project centered around thenewboston?
It enables developers and users to use a MIT licensed app - as well as have this as a developer officially approved app if people wish to spin off a derivative mobile wallet.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
Alpha is done. Milestones / Further features would improve on the alpha release, such that the app is a more feature-rich application.

## Things done:

- [x] create account
- [x] import of privatekey 
- [x] persistence of accounts (encrypted)
- [x] fetching balance 
- [x] update of account balance
- [x] acceptedlist of known confirmed networks (testnet/mainnet) banks/validators and keysign
- [x] clearing persisted storage
- [x] network status
- [x] run `sendCoins` to recipient account

---

## Things to do:

Things to do:

- [ ] plugins
- [ ] friend list 
- [ ] recent transactions
- [ ] adding bank
- [ ] adding friend
- [ ] exporting of accounts (dev-mode + securely)
- [ ] password protect app
- [ ] camera support
- [ ] qr code support (payments transfer+ adding friend + payment request)
- [ ] NFC 
- [ ] integrate tnb-hd-wallet

### Future things to do:

- [ ] support app store/google play release (fastlane etc).
- [ ] jest snapshot testing + detox.
- [ ] tutorials on how to build your own custom mobile app.
- [ ] implement plugin system (integrate with other projects + payment systems)

#### What is your Discord username?
wakawaka#9513

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)

importing key | persisted storage 
--- | --- 
<video src="https://user-images.githubusercontent.com/89671440/139529628-180bdc1e-0136-4b34-8b30-1e6bef0cad9c.mp4" /> | <video src="https://user-images.githubusercontent.com/89671440/139529626-46248026-967b-44a4-8139-3af7af6a4c11.mov" />

UI for accounts + sending coins  | Send Coins 
 --- | ---
<video src="https://user-images.githubusercontent.com/89671440/139529624-1535b61b-1ae3-471d-b5f5-d0882f86b2b8.mp4" /> | <video src="https://user-images.githubusercontent.com/89671440/139540829-49c8bcb8-4d8e-4e03-a038-acff75d95c46.mov" />

# Milestone 1 - Minimum Viable Product (MVP) Details

---

#### MVP Description
The MVP Feature set is to showcase the minimum feature set for the mobile wallet. 
I've tested it on iOS + Android on emulator, but for Milestone 2 I'd like to validate the 

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | MVP Feature set       | [github](https://github.com/wakawakathedev/tnbc_mobile_template) |

Feature set for Milestone 1:
- [x] create account
- [x] import of privatekey 
- [x] persistence of accounts (encrypted)
- [x] fetching balance 
- [x] update of account balance
- [x] acceptedlist of known confirmed networks (testnet/mainnet) banks/validators and keysign
- [x] clearing persisted storage
- [x] network status
- [x] run `sendCoins` to recipient account

#### How long do you estimate for the MVP to complete?
Done.  - need to finish Send coins (Milestone 2 would be 2-3 weeks from now)

#### Project Wallet
`2ecd5ebdfff0ace53bb0f171645f912593b2c9eda722548831a4b32221245525`

**Comment by wakawakathedev** [comment]
Send Coins
https://user-images.githubusercontent.com/89671440/139540829-49c8bcb8-4d8e-4e03-a038-acff75d95c46.mov

**Comment by tspearing** [comment]
Approved.
