### ISSUE TITLE
TNBC Mobile Wallet - MVP Feature set - 1

### ISSUE THREAD

**Issue by wakawakathedev** [thenewboston-developers/Project-Proposals#324]
#### Link to original project proposal.
[Project Proposal](https://github.com/thenewboston-developers/Projects/issues/323)

#### Link to most recent milestone payout request.
[PR](https://github.com/wakawakathedev/tnbc_mobile_template/pull/1)

#### Milestone Description

importing key | persisted storage 
--- | --- 
<video src="https://user-images.githubusercontent.com/89671440/139529628-180bdc1e-0136-4b34-8b30-1e6bef0cad9c.mp4" /> | <video src="https://user-images.githubusercontent.com/89671440/139529626-46248026-967b-44a4-8139-3af7af6a4c11.mov" />

UI for accounts + sending coins  | Send Coins 
 --- | ---
<video src="https://user-images.githubusercontent.com/89671440/139529624-1535b61b-1ae3-471d-b5f5-d0882f86b2b8.mp4" /> | <video src="https://user-images.githubusercontent.com/89671440/139540829-49c8bcb8-4d8e-4e03-a038-acff75d95c46.mov" />

# Milestone 1 - Minimum Viable Product (MVP) Details

---

#### MVP Description
The MVP Feature set is to showcase the minimum feature set for the mobile wallet. 
I've tested it on iOS + Android on emulator, but for Milestone 2 I'd like to validate the 

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | MVP Feature set       | [github](https://github.com/wakawakathedev/tnbc_mobile_template) |

Feature set for Milestone 1:
- [x] create account
- [x] import of privatekey 
- [x] persistence of accounts (encrypted)
- [x] fetching balance 
- [x] update of account balance
- [x] acceptedlist of known confirmed networks (testnet/mainnet) banks/validators and keysign
- [x] clearing persisted storage
- [x] network status
- [x] run `sendCoins` to recipient account

#### How long do you estimate this milestone will take to complete?
Done

#### Project Wallet
`2ecd5ebdfff0ace53bb0f171645f912593b2c9eda722548831a4b32221245525`

**Comment by manishram** [comment]
Hey @wakawakathedev the first milestone(MVP) is already part of your project proposal so no need to have a separate milestone proposal for that. So I am closing this for now. This one is not necessary. We are reviewing your MVP.
