### ISSUE TITLE
tnb-rs - Generating Accounts and Signatures - Milestone 1

### ISSUE THREAD

**Issue by tomijaga** [thenewboston-developers/Project-Proposals#343]
#### Link to the milestone and objectives table.
#334 

#### Detailed log of all completed objectives including valid proof of work.
This milestone has complete implementations for account generation, message signing and signature verification.

**Account**

  - [x] generate random account
  - [x] generate account from signing key
  - [x] create signature
  - [x] verify signature
  - [x] validate key pair
  - [x] create block message
  - [x] create signed message
  
**Hd Wallet**

  - [x] generate hd wallet from mnemonic phrase
  - [x] generate hd wallet from 64 byte seed
  - [x] bip44 standard
  - [x] get account
  
  
[Github Repo]( https://github.com/tomijaga/tnb-rs)
[List of structs and methods in the repo](https://tomijaga.github.io/tnb-rs/tnb_rs/all.html)

[Documentation](https://tomijaga.github.io/tnb-rs/tnb_rs/index.html)
[Tests](https://github.com/tomijaga/tnb-rs/runs/4063024734?check_suite_focus=true)

#### Project Wallet
1c84c8de6c41510150aa5d88df69bb323f7c8bec70578d6d6f78296418af7c7d

**Comment by Kycermann** [comment]
Approved for 45k TNBC.

**Comment by Kycermann** [comment]
For the next milestone, it would be good to add to the documentation how to make new transactions and submit them to a bank. Could you also include an in-library utility to check balances and submit transactions to banks?

**Comment by tomijaga** [comment]
Yh I plan to add those. There will be a wallet client that will handle transactions and all user interactions with the chain. 
There will also be a node client for node owners and maintainers to do the same. Both clients will contain only the necessary methods for completing transactions so that when beta comes there won't be a lot of work going into rewriting them
