### ISSUE TITLE
thenewboston Status Page - For the network

### ISSUE THREAD

**Issue by wakawakathedev** [thenewboston-developers/Project-Proposals#363]
# Project Details

<img width="604" alt="Screenshot 2021-12-01 at 12 22 53 AM" src="https://user-images.githubusercontent.com/89671440/144086453-b64e0808-48ab-4cd8-9887-7d64d712da78.png">

#### How would you describe your project?
It's a status.io page to determine which nodes on the network are currently up/down.

#### What problem does this project solve?
It solves the problem where users have issues asking whether the bank/pv or other node is up.

#### Who is the target market?
users / devs in thenewboston discord

#### How will this project benefit the network and/or the community?
Getting a status page (to debug)

#### How is this project centered around thenewboston?
As titled.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
1-2 Weeks

#### What is your Discord username?
wakawaka#9513 

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)

Milestone 2 / Nice to haves: 
- [ ] The app would crawl through the network (and return the current status).  
- [ ] The app would have a historical status 
- [ ] The app would create a monitor/alert that would be shown in a discord-channel. (e.g. PagerDuty).

# Milestone 1 - Minimum Viable Product (MVP) Details

---

#### MVP Description
Basic status page for viewing the status of the network

#### Objectives for MVP

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Provides A status of the existing nodes of the network | [Deployed](https://thenewboston-status-page.vercel.app/) / [github](https://github.com/wakawakathedev/thenewboston-status-page) |

#### How long do you estimate for the MVP to complete?
Done

#### Project Wallet
`2ecd5ebdfff0ace53bb0f171645f912593b2c9eda722548831a4b32221245525`

**Comment by wakawakathedev** [comment]
> btw the bank is back up again however the status page still showing it down. is it not realtime ?

There seems to be an issue that the cache wasn't invalidating. Will have to attempt to replicate this in a follow up PR

**Comment by tspearing** [comment]
Approved.

**Comment by wakawakathedev** [comment]
I'll create a milestone
