### ISSUE TITLE
tnb-rs - Sending and Retrieving Transactions - Milestone 2

### ISSUE THREAD

**Issue by tomijaga** [thenewboston-developers/Project-Proposals#383]
#### Link to the milestone and objectives table.
[#356 ](https://github.com/thenewboston-developers/Projects/issues/356)

#### Detailed log of all completed objectives including valid proof of work.
This milestone update now supports sending and retrieving transactions from nodes on the network

**Server Node** - [[src]](https://github.com/tomijaga/tnb-rs/blob/master/src/nodes/server_node.rs)
  - [x] GET, POST and PATCH network request methods
  - [x] get config 

**Regular Node** - [[src]](https://github.com/tomijaga/tnb-rs/blob/master/src/nodes/regular_node.rs)
  - [x] connects to the node's url
  - [x] get network transactions
  - [x] transaction query builder for sorting and filtering requests
  - [x] add blocks

**Confimation and Primary Validator Nodes** - [[cv]](https://github.com/tomijaga/tnb-rs/blob/master/src/nodes/confirmation_validator.rs) [[pv]](https://github.com/tomijaga/tnb-rs/blob/master/src/nodes/primary_validator.rs)
  - [x] connects to the node's url
  - [x] get account balance
  - [x] get account balance lock

**Client** - [[src]](https://github.com/tomijaga/tnb-rs/blob/master/src/client.rs)
  - [x] broadcast block
  - [x] update config details 
  - [x] get network fees for setting up transactions
  - [x] get account balance lock
  
**Wallet** - [[src]](https://github.com/tomijaga/tnb-rs/blob/master/src/wallet.rs)
  - [x] send transactions
  - [x] get account balance 
  - [x] switch nodes

  **Models**
  - [x] [tx query builder](https://github.com/tomijaga/tnb-rs/tree/master/src/responses) model
  
**Node Responses** - [[src]](https://github.com/tomijaga/tnb-rs/tree/master/src/responses)
  - [x] account balance response
  - [x] account balance lock response
  - [x] block response
  - [x] config response
  - [x] transaction response
  - [x] paginated response

[Github Repo]( https://github.com/tomijaga/tnb-rs)
[List of structs and methods in the repo](https://tomijaga.github.io/tnb-rs/tnb_rs/all.html)

[Documentation](https://tomijaga.github.io/tnb-rs/tnb_rs/index.html)
[Tests](https://github.com/tomijaga/tnb-rs/runs/4515923850?check_suite_focus=true#step:4:194)

#### Project Wallet
1c84c8de6c41510150aa5d88df69bb323f7c8bec70578d6d6f78296418af7c7d

**Comment by manishram** [comment]
Approved for 50k
